apiVersion: v1
kind: Secret
{{- $name := printf "%s-db-worker" (include "corda.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ $name }}
  labels:
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
data:
{{- if $existingSecret }}
  salt: {{ index $existingSecret.data "salt" }}
  passphrase: {{ index $existingSecret.data "passphrase" }}
{{- if .Values.db.secret.salt }}
  salt: {{ .Values.db.secret.salt | b64enc | quote }}
  passphrase: {{ .Values.db.secret.passphrase | b64enc | quote }}
{{- else }}
  salt: {{ randAlphaNum 32 | b64enc | quote }}
  passphrase: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}